### ISSUE TITLE
Support light theme

### ISSUE THREAD

**Issue by awissu** [Dirli/pantheon-monitor#1]
Hi! I would like to publish the package for openSUSE, but bumped on problem:
![Снимок экрана от 2019-04-16 07 41 52](https://user-images.githubusercontent.com/8833364/56182666-e1c9e800-601b-11e9-8b76-9ba28c3af258.png)

**Comment by Dirli** [comment]
Hi. It is a bad idea. I do not plan to develop this project yet. I combined two third-party projects:
https://github.com/stsdc/monitor
https://github.com/kmal-kenneth/monilet
, and wrote an indicator (to monitor memory when updating a Gentoo). I just needed an indicator))) I really hope that the author of the monitor, in the future, will implement something similar.
Although if I have time, I will try to finish the job, including by adding disk monitoring. But not now))
This does not apply to pantheon-meteo, where the author refused to support the package in the form that corresponded to my ideas. I rewrote this project a little and can support it))

**Comment by awissu** [comment]
Oh, i understand... 
For now, feel free to close this report.

**Comment by Dirli** [comment]
If you wish, test the indicator-places. Hands do not reach yet to check on the OpenSUSE. And in Debian and Gentoo - different behavior. In particular, wonders if the rule works when mounting volumes?

**Comment by awissu** [comment]
> In particular, wonders if the rule works when mounting volumes?

Yes.
Already checked and published:
https://software.opensuse.org/package/wingpanel-indicator-cpufreq?search_term=wingpanel-indicator-cpufreq
https://software.opensuse.org/package/wingpanel-indicator-places?search_term=wingpanel-indicator-places
https://software.opensuse.org/package/wingpanel-indicator-sensors?search_term=wingpanel-indicator-sensors
