### ISSUE TITLE
Не правильный размер значков в панели

### ISSUE THREAD

**Issue by varlesh** [Dirli/pantheon-monitor#2]
Здравствуйте. В большинстве ваших индикаторов используется не верный размер индикатора в панели:
`Gtk.IconSize.LARGE_TOOLBAR`
Что согласно [документации](https://valadoc.org/gtk+-3.0/Gtk.IconSize.LARGE_TOOLBAR.html), как бы верно и по дефолту elementary использует 24px-symbolic значки для панели.

Но индикатор выглядит увеличенным, из-за того что исходный размер значка 16px:
![Снимок экрана от 2020-05-27 09-45-20](https://user-images.githubusercontent.com/8083855/82983217-c728b780-a000-11ea-8274-08c052f21361.png)
Логичней было бы использовать 16px, потому как исходник 16px (и что соответствует status или devices) + не будет ломать совместимость с другими темами значков, т.к. обычно 16px юзается везде.
`Gtk.IconSize.SMALL_TOOLBAR`
Собственно, пример:
![Снимок экрана от 2020-05-27 10-05-36](https://user-images.githubusercontent.com/8083855/82983712-a9a81d80-a001-11ea-9fb9-905a409afb68.png)
Так же, значки стоит выравнять по пиксельной сетке (что бы не было размытия):
![Снимок экрана от 2020-05-27 10-08-00](https://user-images.githubusercontent.com/8083855/82983909-16bbb300-a002-11ea-9ffe-d1b7dddb3335.png)
Для примера, вот тоже похожая программа:
https://github.com/PlugaruT/wingpanel-monitor/blob/master/src/Widgets/IndicatorWidget.vala#L37

**Comment by varlesh** [comment]
могу запилить PR, если нужно

**Comment by varlesh** [comment]
Список виджетов для фикса:
https://github.com/Dirli/wingpanel-indicator-places/blob/master/src/Indicator.vala#L36
https://github.com/Dirli/wingpanel-indicator-sensors/blob/master/src/Indicator.vala#L34
https://github.com/Dirli/pantheon-monitor/blob/master/src/Widgets/Panel.vala#L29
https://github.com/Dirli/pantheon-monitor/blob/master/src/Widgets/Panel.vala#L34
https://github.com/Dirli/wingpanel-indicator-workspaces/blob/master/src/Widgets/Panel.vala#L26

**Comment by varlesh** [comment]
Значки для  places и sensors. Все почищено и выровнено по пикселям
[icons.zip](https://github.com/Dirli/pantheon-monitor/files/4687227/icons.zip)

**Comment by Dirli** [comment]
Здравствуйте, Спасибо за проделанную работу. Ваши замечания уместны. Иконки делал первый раз в жизни (надеюсь последний), сделал как смог за ограниченное время)
Для places, брал иконку из стандартной темы, так что с изменениями в ней не ко мне.
По размеру places и workspaces пока точно не могу понять как лучше, такое ощущение, что есть зависимость от размера монитора)
Если не затруднит, можете сделать PR.

**Comment by varlesh** [comment]
для places я сделал из сдвоенных папок (из родных), оно  по стилю и смыслу похоже.
Сделаю PR, без проблем.

**Comment by varlesh** [comment]
по поводу workspaces. Оригинальный значок имеет размер 16x15. Потому может казаться, что он меньше других. Хотя не критично 1px всего
![image](https://user-images.githubusercontent.com/8083855/83021784-974ad580-a03b-11ea-8e60-470fe9f75e33.png)

**Comment by varlesh** [comment]
Для workspaces можно просто нарисовать рамку с закругленными углами
![image](https://user-images.githubusercontent.com/8083855/83028326-50141300-a042-11ea-8164-0d0b30887b47.png)

**Comment by Dirli** [comment]
Да, хорошая идея

**Comment by varlesh** [comment]
@Dirli Добрый утро) Сообщение не по теме и все таки...
Есть идея хорошего и полезного индикатора "Скорость передачи данных" или как говорят в народе NetSpeed Indicator. Подобный индикатор уже есть в https://github.com/PlugaruT/wingpanel-monitor
Но разработчик видимо не задается мыслью о том, что он отнимает просто неимоверное количество полезного пространства:
![image](https://user-images.githubusercontent.com/8083855/83095885-60b1a100-a0b5-11ea-9e9e-1ccfdd17fe37.png)
Идея заключается в том, что бы сделать его компактным и читаемым. Как пример
![image](https://user-images.githubusercontent.com/8083855/83095957-83dc5080-a0b5-11ea-8fda-6d935e4cf8b6.png)
Теперь поближе:
![image](https://user-images.githubusercontent.com/8083855/83096009-a3737900-a0b5-11ea-8e54-1b0fb7324ac9.png)
- красным выделен обычный значок 16px обозначающий снизу загрузку, сверху отдачу.
- синим выделена область текста скорости загрузки
- зеленым выделена область текста скорости отдачи
- небольшие отступы в 2px

надеюсь wingpanel поддерживает 2 строчки или может какой обходной путь для этого есть

**Comment by Dirli** [comment]
![screen8px](https://user-images.githubusercontent.com/15650716/83128500-32978580-a0e4-11ea-9122-105c5df67fe2.png)
![screen9px](https://user-images.githubusercontent.com/15650716/83128510-375c3980-a0e4-11ea-9d9d-7a1a53c0dcc0.png)

**Comment by Dirli** [comment]
![screen8px (1)](https://user-images.githubusercontent.com/15650716/83128567-44792880-a0e4-11ea-8871-62883197c0bc.png)
![screen9px (1)](https://user-images.githubusercontent.com/15650716/83128577-480caf80-a0e4-11ea-8cd0-5e0146af5275.png)

**Comment by Dirli** [comment]
в первом коменте не прозрачная панель 8 и 9 px
во втором прозрачная.так же 8 и 9
если делать шрифт больше, то начнет растягиваться панель, по крайней мере у меня так,

**Comment by varlesh** [comment]
Ну куда лучше, чем значок занимающий половину панели.
Возможно для обхода подобной проблемы сделать ползунок для регулировки размера шрифта в настройках виджета.

**Comment by varlesh** [comment]
Ой, я походу вас не понял)) Думал при смене шрифта в системе растягивается панель, а вы мне говорите, что макимальный размер 8 и 9px.
Не знаю, как оно смотрится на 4K мониторах. Но на обычном FHD вполне классно и компактно

**Comment by varlesh** [comment]
Значки на ваш вкус:
[icons.tar.gz](https://github.com/Dirli/pantheon-monitor/files/4695681/icons.tar.gz)

![image](https://user-images.githubusercontent.com/8083855/83145184-7b136b00-a105-11ea-9f74-5652a9f1fc39.png)

**Comment by Dirli** [comment]
Идеально было бы если бы это было 4 значка. Активны обе стрелки, активна одна из стрелок (цвет разный), обе не активны. В остальном не принципиально. Дизайн это прям совсем не мое, мне главное чтобы работало)

**Comment by Dirli** [comment]
Я за 3))

**Comment by varlesh** [comment]
ок, скоро скину

**Comment by varlesh** [comment]
[icons_2.tar.gz](https://github.com/Dirli/pantheon-monitor/files/4695918/icons_2.tar.gz)
![image](https://user-images.githubusercontent.com/8083855/83150061-e95b2c00-a10b-11ea-9419-34cd4d507c12.png)

**Comment by varlesh** [comment]
> (цвет разный)

Думаю не самый лучший вариант, т.к. обычно используют монохром. Для определенного цвето можно прописать класс CSS... но не уверен что это будет смотреться. Добавил просто непрозрачная на 35% - не активна, непрозрачна на 100% - активна. (как и остальные значки типа volume, wifi  и т.д.)

**Comment by Dirli** [comment]
Да, я это и имел ввиду) мы поняли друг друга. Спасибо.

**Comment by Dirli** [comment]
Спасибо за идею и иконки, вроде неплохо получилось, по крайней мере я вполне удовлетворен.

**Comment by varlesh** [comment]
@Dirli Выглядит отлично. Но думаю стоит выделить место под него, т.к. при изменении значений индикаторы скачут влево-вправо
![Запись экрана от 2020-05-29 08 34 07](https://user-images.githubusercontent.com/8083855/83221619-5364e700-a187-11ea-8e65-822e6d6762a8.gif)

В качестве компромисса стоит убрать сотые значения после запятой, что сэкономит место. --~~Они все время равны нулям, да и смысла в них особого нет~~
UPD: извиняюсь, значения меняются.... но наверное это только актуально для мегабайт. Для байт и килобайт не принципиально

**Comment by varlesh** [comment]
@Dirli Спасибо, все классно!

**Comment by Dirli** [comment]
Все таки добавил возможность менять размер шрифта.
